name: Build X00TD Kernel

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-kernel:
    name: Build Kernel
    runs-on: ubuntu-22.04
    steps:
      - name: Build
        uses: dabao1955/kernel_build_action@main
        with:
          kernel-url: https://github.com/arazy79/android_kernel_asus_sdm660
          kernel-branch: r7/hmp
          config: X00TD_defconfig
          arch: arm64
          android-version: 11
          aosp-gcc: false
          aosp-clang: false
          other-clang-url: https://gitlab.com/ThankYouMario/android_prebuilts_clang-standalone
          other-clang-branch: "11"
          anykernel3: true
          anykernel3-url: https://github.com/RyuujiX/AnyKernel3
          release: false
          extra-make-args: '["CROSS_COMPILE=aarch64-linux-gnu-", "CROSS_COMPILE_ARM32=arm-linux-gnueabi-", "CLANG_TRIPLE=aarch64-linux-gnu-"]'
